# fly.toml app configuration file generated for tda on 2023-06-21T12:29:59-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "tda"
primary_region = "bos"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0

[processes]
  # The command below is used to launch a Rails server; be sure to
  # replace with the command you're using to launch your server.
  # web = "bin/rails fly:server"
  cron = "supercronic crontab"

# Make sure there's only one `processes` entry under `[[services]]`
# [[services]]
#   processes = ["web"]
